---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "safe-client-gateway.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "safe-client-gateway.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- .Values.commonLabels | toYaml | nindent 4 }}
    {{- end }}
{{- if .Values.commonAnnotations }}
  annotations:
    {{- .Values.commonAnnotations | toYaml | nindent 4 }}
{{- end }}
data:
  APPLICATION_PORT: {{ .Values.service.ports.number | quote }}
  SAFE_CONFIG_BASE_URI: {{ .Values.config.safeConfig.url | quote }}
  REDIS_HOST: {{ .Values.config.redis.host | quote }}
  REDIS_PORT: {{ .Values.config.redis.port | toString | quote }}
  FINGERPRINT_ENCRYPTION_KEY: ''
  RELAY_PROVIDER_API_KEY_OPTIMISM: ''
  RELAY_PROVIDER_API_KEY_BSC: ''
  RELAY_PROVIDER_API_KEY_POLYGON: ''
  RELAY_PROVIDER_API_KEY_POLYGON_ZKEVM: ''
  RELAY_PROVIDER_API_KEY_BASE: ''
  RELAY_PROVIDER_API_KEY_AVALANCHE: ''
  RELAY_PROVIDER_API_KEY_LINEA: ''
  RELAY_PROVIDER_API_KEY_BLAST: ''
  STAKING_API_KEY: ''
  STAKING_TESTNET_API_KEY: ''
  EMAIL_API_APPLICATION_CODE: ''
  EMAIL_API_FROM_EMAIL: 'tech@hoprnet.org'
  EMAIL_API_KEY: ''
  EMAIL_TEMPLATE_RECOVERY_TX: ''
  EMAIL_TEMPLATE_UNKNOWN_RECOVERY_TX: ''
  EMAIL_TEMPLATE_VERIFICATION_CODE: ''
  INFURA_API_KEY: ''
  PUSH_NOTIFICATIONS_API_PROJECT: ''
  PUSH_NOTIFICATIONS_API_SERVICE_ACCOUNT_CLIENT_EMAIL: 'tech@hoprnet.org'
  PUSH_NOTIFICATIONS_API_SERVICE_ACCOUNT_PRIVATE_KEY: ''
  RELAY_PROVIDER_API_KEY_GNOSIS_CHAIN: ''
  RELAY_PROVIDER_API_KEY_ARBITRUM_ONE: ''
  RELAY_PROVIDER_API_KEY_SEPOLIA: ''
  CSV_AWS_ACCESS_KEY_ID: ""
  CSV_AWS_SECRET_ACCESS_KEY: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  BRIDGE_API_KEY: ""
  BLOCKLIST_ENABLED: "false"
  BLOCKLIST_ENCRYPTED_DATA: dummy-encrypted-data
  BLOCKLIST_SECRET_KEY: 5403fdc3516efd310429ad84d105d428aaa633b1e1e74e0329c8929dc6733139
  BLOCKLIST_SECRET_SALT: c29199c8a64cf0bfa1f8c86754d4bb33
  RELAY_PROVIDER_API_KEY_UNICHAIN: dummy-api-key
  {{- if .Values.config.extraEnvVars -}}
  {{ .Values.config.extraEnvVars | toYaml | nindent 2 }}
  {{- end }}
